AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters: 
  keyPair:
    Description: Choose your key
    Type: AWS::EC2::KeyPair::KeyName
    Default: betulk

  instanceType:
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
    Type: String
    Default: t3.micro
    AllowedValues:
      - t2.micro
      - t3.small
      - t3.micro

  imageID:
    Description: Name of a Parameter Store parameter that stores the ID of the Amazon Machine Image (AMI).
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-arm64    

Resources:
  mysecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ssh and http # Required
      GroupName: betul-kitten-project-scgrp
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: tcp
          ToPort: 22
  MyWebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref imageID
      InstanceType: !Ref instanceType
      KeyName: !Ref keyPair
      SecurityGroupIds: 
        - "String"
      SecurityGroups: 
        - "String"
      Tags: 
        - Key: "String"
          Value: "String"
      UserData: !Base64 |
        #! /bin/bash
        dnf update -y
        dnf install httpd -y
        chmod 777 /var/www/html
        cd /var/www/html
        dnf install git -y
        git clone https://github.com/betul-kaplan/aws-projects.git

  
Outputs: